version: "3.8"
services:

  # php
  php:
    container_name: php
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - database

  # database
  database:
    container_name: database
    image: mysql:8.2
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: ~
